#############################################################################
# Makefile for building: database
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  database.pro
# Template: subdirs
# Command: C:\Qt\Qt5.5.0\5.5\mingw492_32\bin\qmake.exe -o Makefile database.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\Qt5.5.0\5.5\mingw492_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-src


sub-src-qmake_all:  FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile
	cd src\ && $(MAKE) -f Makefile qmake_all
sub-src: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile
sub-src-make_first: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile 
sub-src-all: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile all
sub-src-clean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile clean
sub-src-distclean: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile distclean
sub-src-install_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile install
sub-src-uninstall_subtargets: FORCE
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: database.pro .qmake.cache ../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf ../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/spec_pre.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/qdevice.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/device_config.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/qconfig.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_functions.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_config.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/qt_config.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/spec_post.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/default_pre.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/default_pre.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/qmodule.pri \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_build_config.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_parts.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/resolve_config.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/exclusive_builds_post.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/default_post.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/exceptions_off.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_docs_targets.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/rtti.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/precompile_header.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/warn_on.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/windows.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/testcase_targets.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/yacc.prf \
		../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/lex.prf \
		database.pro
	$(QMAKE) -o Makefile database.pro
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/spec_pre.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/qdevice.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/device_config.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/qconfig.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axbase_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_axserver_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_declarative_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_enginio_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_script.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkit_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_winextras_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_functions.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_config.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/qt_config.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/win32-g++/qmake.conf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/spec_post.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/exclusive_builds.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/default_pre.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/default_pre.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/qmodule.pri:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_build_config.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_parts.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/resolve_config.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/exclusive_builds_post.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/default_post.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/exceptions_off.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/qt_docs_targets.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/rtti.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/precompile_header.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/warn_on.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/win32/windows.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/testcase_targets.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/yacc.prf:
../../../../Qt/Qt5.5.0/5.5/mingw492_32/mkspecs/features/lex.prf:
database.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile database.pro

qmake_all: sub-src-qmake_all FORCE

make_first: sub-src-make_first  FORCE
all: sub-src-all  FORCE
clean: sub-src-clean  FORCE
distclean: sub-src-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.cache config.log mkspecs\modules\*.pri mkspecs\modules-inst\*.pri
install_subtargets: sub-src-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets FORCE

sub-src-debug:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-src-debug

sub-src-release:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile release
release: sub-src-release

html_docs:
	$(MAKE) -f $(MAKEFILE) prepare_docs && $(MAKE) -f $(MAKEFILE) generate_docs

docs:
	$(MAKE) -f $(MAKEFILE) html_docs && $(MAKE) -f $(MAKEFILE) qch_docs

sub-src-install_html_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile install_html_docs
install_html_docs: sub-src-install_html_docs

sub-src-uninstall_html_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_html_docs
uninstall_html_docs: sub-src-uninstall_html_docs

sub-src-install_qch_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile install_qch_docs
install_qch_docs: sub-src-install_qch_docs

sub-src-uninstall_qch_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_qch_docs
uninstall_qch_docs: sub-src-uninstall_qch_docs

sub-src-install_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile install_docs
install_docs: sub-src-install_docs

sub-src-uninstall_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile uninstall_docs
uninstall_docs: sub-src-uninstall_docs

sub-src-qch_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile qch_docs
qch_docs: sub-src-qch_docs

sub-src-prepare_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile prepare_docs
prepare_docs: sub-src-prepare_docs

sub-src-generate_docs:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile generate_docs
generate_docs: sub-src-generate_docs

sub-src-check:
	@if not exist src\ mkdir src\ & if not exist src\ exit 1
	cd src\ && ( if not exist Makefile $(QMAKE) C:\Users\jorgenio\Desktop\database\src\src.pro -o Makefile ) && $(MAKE) -f Makefile check
check: sub-src-check
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

